// This file was auto-generated by ML.NET Model Builder. 

using System;
using Kinect_Science_FairML.Model;

namespace Kinect_Science_FairML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                _0 = 0.82F,
                _1 = 0.86F,
                _2 = 0.86F,
                _3 = 0.9F,
                _4 = 0.9F,
                _5 = 0.9F,
                _6 = 0.92F,
                _7 = 0.96F,
                _8 = 0.96F,
                _9 = 1F,
                _10 = 1F,
                _11 = 0.96F,
                _12 = 1F,
                _13 = 0.96F,
                _14 = 0.96F,
                _15 = 0.92F,
                _16 = 0.96F,
                _17 = 0.92F,
                _18 = 0.92F,
                _19 = 0.96F,
                _20 = 0.92F,
                _21 = 0.92F,
                _22 = 0.92F,
                _23 = 0.92F,
                _24 = 0.9F,
                _25 = 0.9F,
                _26 = 0.86F,
                _27 = 0.86F,
                _28 = 0.86F,
                _29 = 0.9F,
                _30 = 0.9F,
                _31 = 0.9F,
                _32 = 0.9F,
                _33 = 0.92F,
                _34 = 0.96F,
                _35 = 0.96F,
                _36 = 0.92F,
                _37 = 0.86F,
                _38 = 0.82F,
                _39 = 0.86F,
                _40 = 0.86F,
                _41 = 0.9F,
                _42 = 0.86F,
                _43 = 0.82F,
                _44 = 0.86F,
                _45 = 0.92F,
                _46 = 0.92F,
                _47 = 0.9F,
                _48 = 0.86F,
                _49 = 0.86F,
                _50 = 0.9F,
                _51 = 0.9F,
                _52 = 0.9F,
                _53 = 0.86F,
                _54 = 0.86F,
                _55 = 0.86F,
                _56 = 0.9F,
                _57 = 0.92F,
                _58 = 0.92F,
                _59 = 0.92F,
                _60 = 0.9F,
                _61 = 0.86F,
                _62 = 0.9F,
                _63 = 0.9F,
                _64 = 0.9F,
                _65 = 0.86F,
                _66 = 0.86F,
                _67 = 0.86F,
                _68 = 0.86F,
                _69 = 0.86F,
                _70 = 0.86F,
                _71 = 0.86F,
                _72 = 0.86F,
                _73 = 0.86F,
                _74 = 0.86F,
                _75 = 0.86F,
                _76 = 0.86F,
                _77 = 0.82F,
                _78 = 0.86F,
                _79 = 0.86F,
                _80 = 0.86F,
                _81 = 0.86F,
                _82 = 0.9F,
                _83 = 0.9F,
                _84 = 0.9F,
                _85 = 0.9F,
                _86 = 0.92F,
                _87 = 0.92F,
                _88 = 0.9F,
                _89 = 0.9F,
                _90 = 0.9F,
                _91 = 0.9F,
                _92 = 0.9F,
                _93 = 0.9F,
                _94 = 0.86F,
                _95 = 0.86F,
                _96 = 0.86F,
                _97 = 0.86F,
                _98 = 0.86F,
                _99 = 0.9F,
                _100 = 0.86F,
                _101 = 0.86F,
                _102 = 0.86F,
                _103 = 0.9F,
                _104 = 0.9F,
                _105 = 0.9F,
                _106 = 0.9F,
                _107 = 0.86F,
                _108 = 0.9F,
                _109 = 0.86F,
                _110 = 0.86F,
                _111 = 0.86F,
                _112 = 0.82F,
                _113 = 0.82F,
                _114 = 0.82F,
                _115 = 0.82F,
                _116 = 0.82F,
                _117 = 0.82F,
                _118 = 0.82F,
                _119 = 0.82F,
                _120 = 0.86F,
                _121 = 0.86F,
                _122 = 0.86F,
                _123 = 0.86F,
                _124 = 0.9F,
                _125 = 0.9F,
                _126 = 0.9F,
                _127 = 0.92F,
                _128 = 0.92F,
                _129 = 0.92F,
                _130 = 0.96F,
                _131 = 0.96F,
                _132 = 0.96F,
                _133 = 0.96F,
                _134 = 0.96F,
                _135 = 0.96F,
                _136 = 0.96F,
                _137 = 0.96F,
                _138 = 0.96F,
                _139 = 0.96F,
                _140 = 0.96F,
                _141 = 0.96F,
                _142 = 0.92F,
                _143 = 0.92F,
                _144 = 0.92F,
                _145 = 0.9F,
                _146 = 0.86F,
                _147 = 0.82F,
                _148 = 0.86F,
                _149 = 0.9F,
                _150 = 0.86F,
                _151 = 0.86F,
                _152 = 0.82F,
                _153 = 0.82F,
                _154 = 0.86F,
                _155 = 0.86F,
                _156 = 0.86F,
                _157 = 0.82F,
                _158 = 0.82F,
                _159 = 0.82F,
                _160 = 0.86F,
                _161 = 0.86F,
                _162 = 0.86F,
                _163 = 0.82F,
                _164 = 0.86F,
                _165 = 0.86F,
                _166 = 0.9F,
                _167 = 0.86F,
                _168 = 0.86F,
                _169 = 0.86F,
                _170 = 0.9F,
                _171 = 0.92F,
                _172 = 0.96F,
                _173 = 0.96F,
                _174 = 0.96F,
                _175 = 0.92F,
                _176 = 0.92F,
                _177 = 0.92F,
                _178 = 0.9F,
                _179 = 0.86F,
                _180 = 0.86F,
                _181 = 0.86F,
                _182 = 0.86F,
                _183 = 0.86F,
                _184 = 0.86F,
                _185 = 0.86F,
                _186 = 0.82F,
                _187 = 0.82F,
                _188 = 0.82F,
                _189 = 0.82F,
                _190 = 0.86F,
                _191 = 0.86F,
                _192 = 0.86F,
                _193 = 0.86F,
                _194 = 0.86F,
                _195 = 0.9F,
                _196 = 0.86F,
                _197 = 0.86F,
                _198 = 0.86F,
                _199 = 0.86F,
                _200 = 0.86F,
                _201 = 0.86F,
                _202 = 0.86F,
                _203 = 0.86F,
                _204 = 0.86F,
                _205 = 0.82F,
                _206 = 0.82F,
                _207 = 0.8F,
                _208 = 0.8F,
                _209 = 0.8F,
                _210 = 0.8F,
                _211 = 0.76F,
                _212 = 0.72F,
                _213 = 0.66F,
                _214 = 0.62F,
                _215 = 0.62F,
                _216 = 0.62F,
                _217 = 0.6F,
                _218 = 0.56F,
                _219 = 0.16F,
                _220 = 0.16F,
                _221 = 0.16F,
                _222 = 0.16F,
                _223 = 0.18F,
                _224 = 0.18F,
                _225 = 0.16F,
                _226 = 0.12F,
                _227 = 0.12F,
                _228 = 0.04F,
                _229 = 0.04F,
                _230 = 0.04F,
                _231 = 0.04F,
                _232 = 0F,
                _233 = 0.04F,
                _234 = 0.28F,
                _235 = 0.32F,
                _236 = 0.34F,
                _237 = 0.34F,
                _238 = 0.38F,
                _239 = 0.38F,
                _240 = 0.38F,
                _241 = 0.38F,
                _242 = 0.4F,
                _243 = 0.4F,
                _244 = 0.4F,
                _245 = 0.44F,
                _246 = 0.44F,
                _247 = 0.4F,
                _248 = 0.4F,
                _249 = 0.4F,
                _250 = 0.38F,
                _251 = 0.38F,
                _252 = 0.38F,
                _253 = 0.34F,
                _254 = 0.38F,
                _255 = 0.38F,
                _256 = 0.4F,
                _257 = 0.38F,
                _258 = 0.38F,
                _259 = 0.38F,
                _260 = 0.38F,
                _261 = 0.34F,
                _262 = 0.32F,
                _263 = 0.28F,
                _264 = 0.72F,
                _265 = 0.72F,
                _266 = 0.76F,
                _267 = 0.76F,
                _268 = 0.76F,
                _269 = 0.8F,
                _270 = 0.8F,
                _271 = 0.8F,
                _272 = 0.8F,
                _273 = 0.8F,
                _274 = 0.76F,
                _275 = 0.76F,
                _276 = 0.8F,
                _277 = 0.8F,
                _278 = 0.8F,
                _279 = 0.82F,
                _280 = 0.82F,
                _281 = 0.82F,
                _282 = 0.82F,
                _283 = 0.82F,
                _284 = 0.8F,
                _285 = 0.8F,
                _286 = 0.8F,
                _287 = 0.8F,
                _288 = 0.8F,
                _289 = 0.8F,
                _290 = 0.8F,
                _291 = 0.8F,
                _292 = 0.82F,
                _293 = 0.82F,
                _294 = 0.82F,
                _295 = 0.8F,
                _296 = 0.8F,
                _297 = 0.76F,
                _298 = 0.76F,
                _299 = 0.76F,
                _300 = 0.72F,
                _301 = 0.72F,
                _302 = 0.72F,
                _303 = 0.72F,
                _304 = 0.72F,
                _305 = 0.72F,
                _306 = 0.72F,
                _307 = 0.72F,
                _308 = 0.72F,
                _309 = 0.72F,
                _310 = 0.7F,
                _311 = 0.7F,
                _312 = 0.72F,
                _313 = 0.72F,
                _314 = 0.72F,
                _315 = 0.72F,
                _316 = 0.72F,
                _317 = 0.72F,
                _318 = 0.7F,
                _319 = 0.7F,
                _320 = 0.7F,
                _321 = 0.7F,
                _322 = 0.7F,
                _323 = 0.7F,
                _324 = 0.72F,
                _325 = 0.76F,
                _326 = 0.76F,
                _327 = 0.76F,
                _328 = 0.76F,
                _329 = 0.72F,
                _330 = 0.72F,
                _331 = 0.72F,
                _332 = 0.72F,
                _333 = 0.72F,
                _334 = 0.72F,
                _335 = 0.76F,
                _336 = 0.72F,
                _337 = 0.72F,
                _338 = 0.72F,
                _339 = 0.72F,
                _340 = 0.7F,
                _341 = 0.7F,
                _342 = 0.7F,
                _343 = 0.7F,
                _344 = 0.7F,
                _345 = 0.7F,
                _346 = 0.7F,
                _347 = 0.7F,
                _348 = 0.7F,
                _349 = 0.7F,
                _350 = 0.7F,
                _351 = 0.66F,
                _352 = 0.66F,
                _353 = 0.7F,
                _354 = 0.7F,
                _355 = 0.66F,
                _356 = 0.66F,
                _357 = 0.66F,
                _358 = 0.66F,
                _359 = 0.62F,
                _360 = 0.62F,
                _361 = 0.66F,
                _362 = 0.66F,
                _363 = 0.66F,
                _364 = 0.7F,
                _365 = 0.66F,
                _366 = 0.7F,
                _367 = 0.7F,
                _368 = 0.7F,
                _369 = 0.66F,
                _370 = 0.66F,
                _371 = 0.66F,
                _372 = 0.66F,
                _373 = 0.66F,
                _374 = 0.62F,
                _375 = 0.62F,
                _376 = 0.62F,
                _377 = 0.62F,
                _378 = 0.62F,
                _379 = 0.62F,
                _380 = 0.62F,
                _381 = 0.62F,
                _382 = 0.62F,
                _383 = 0.66F,
                _384 = 0.66F,
                _385 = 0.7F,
                _386 = 0.7F,
                _387 = 0.7F,
                _388 = 0.66F,
                _389 = 0.62F,
                _390 = 0.66F,
                _391 = 0.6F,
                _392 = 0.6F,
                _393 = 0.62F,
                _394 = 0.56F,
                _395 = 0.6F,
                _396 = 0.6F,
                _397 = 0.6F,
                _398 = 0.62F,
                _399 = 0.62F,
                _400 = 0.62F,
                _401 = 0.6F,
                _402 = 0.62F,
                _403 = 0.6F,
                _404 = 0.62F,
                _405 = 0.66F,
                _406 = 0.7F,
                _407 = 0.72F,
                _408 = 0.7F,
                _409 = 0.7F,
                _410 = 0.62F,
                _411 = 0.7F,
                _412 = 0.66F,
                _413 = 0.66F,
                _414 = 0.62F,
                _415 = 0.62F,
                _416 = 0.62F,
                _417 = 0.62F,
                _418 = 0.62F,
                _419 = 0.62F,
                _420 = 0.6F,
                _421 = 0.62F,
                _422 = 0.62F,
                _423 = 0.62F,
                _424 = 0.6F,
                _425 = 0.6F,
                _426 = 0.62F,
                _427 = 0.6F,
                _428 = 0.6F,
                _429 = 0.6F,
                _430 = 0.6F,
                _431 = 0.62F,
                _432 = 0.6F,
                _433 = 0.62F,
                _434 = 0.66F,
                _435 = 0.66F,
                _436 = 0.6F,
                _437 = 0.6F,
                _438 = 0.56F,
                _439 = 0.6F,
                _440 = 0.56F,
                _441 = 0.54F,
                _442 = 0.54F,
                _443 = 0.54F,
                _444 = 0.54F,
                _445 = 0.56F,
                _446 = 0.56F,
                _447 = 0.56F,
                _448 = 0.54F,
                _449 = 0.54F,
                _450 = 0.54F,
                _451 = 0.54F,
                _452 = 0.56F,
                _453 = 0.56F,
                _454 = 0.56F,
                _455 = 0.56F,
                _456 = 0.6F,
                _457 = 0.6F,
                _458 = 0.6F,
                _459 = 0.56F,
                _460 = 0.56F,
                _461 = 0.56F,
                _462 = 0.56F,
                _463 = 0.54F,
                _464 = 0.54F,
                _465 = 0.56F,
                _466 = 0.54F,
                _467 = 0.54F,
                _468 = 0.54F,
                _469 = 0.54F,
                _470 = 0.56F,
                _471 = 0.56F,
                _472 = 0.56F,
                _473 = 0.56F,
                _474 = 0.54F,
                _475 = 0.54F,
                _476 = 0.54F,
                _477 = 0.54F,
                _478 = 0.54F,
                _479 = 0.5F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Target with predicted Target from sample data...\n\n");
            Console.WriteLine($"_0: {sampleData._0}");
            Console.WriteLine($"_1: {sampleData._1}");
            Console.WriteLine($"_2: {sampleData._2}");
            Console.WriteLine($"_3: {sampleData._3}");
            Console.WriteLine($"_4: {sampleData._4}");
            Console.WriteLine($"_5: {sampleData._5}");
            Console.WriteLine($"_6: {sampleData._6}");
            Console.WriteLine($"_7: {sampleData._7}");
            Console.WriteLine($"_8: {sampleData._8}");
            Console.WriteLine($"_9: {sampleData._9}");
            Console.WriteLine($"_10: {sampleData._10}");
            Console.WriteLine($"_11: {sampleData._11}");
            Console.WriteLine($"_12: {sampleData._12}");
            Console.WriteLine($"_13: {sampleData._13}");
            Console.WriteLine($"_14: {sampleData._14}");
            Console.WriteLine($"_15: {sampleData._15}");
            Console.WriteLine($"_16: {sampleData._16}");
            Console.WriteLine($"_17: {sampleData._17}");
            Console.WriteLine($"_18: {sampleData._18}");
            Console.WriteLine($"_19: {sampleData._19}");
            Console.WriteLine($"_20: {sampleData._20}");
            Console.WriteLine($"_21: {sampleData._21}");
            Console.WriteLine($"_22: {sampleData._22}");
            Console.WriteLine($"_23: {sampleData._23}");
            Console.WriteLine($"_24: {sampleData._24}");
            Console.WriteLine($"_25: {sampleData._25}");
            Console.WriteLine($"_26: {sampleData._26}");
            Console.WriteLine($"_27: {sampleData._27}");
            Console.WriteLine($"_28: {sampleData._28}");
            Console.WriteLine($"_29: {sampleData._29}");
            Console.WriteLine($"_30: {sampleData._30}");
            Console.WriteLine($"_31: {sampleData._31}");
            Console.WriteLine($"_32: {sampleData._32}");
            Console.WriteLine($"_33: {sampleData._33}");
            Console.WriteLine($"_34: {sampleData._34}");
            Console.WriteLine($"_35: {sampleData._35}");
            Console.WriteLine($"_36: {sampleData._36}");
            Console.WriteLine($"_37: {sampleData._37}");
            Console.WriteLine($"_38: {sampleData._38}");
            Console.WriteLine($"_39: {sampleData._39}");
            Console.WriteLine($"_40: {sampleData._40}");
            Console.WriteLine($"_41: {sampleData._41}");
            Console.WriteLine($"_42: {sampleData._42}");
            Console.WriteLine($"_43: {sampleData._43}");
            Console.WriteLine($"_44: {sampleData._44}");
            Console.WriteLine($"_45: {sampleData._45}");
            Console.WriteLine($"_46: {sampleData._46}");
            Console.WriteLine($"_47: {sampleData._47}");
            Console.WriteLine($"_48: {sampleData._48}");
            Console.WriteLine($"_49: {sampleData._49}");
            Console.WriteLine($"_50: {sampleData._50}");
            Console.WriteLine($"_51: {sampleData._51}");
            Console.WriteLine($"_52: {sampleData._52}");
            Console.WriteLine($"_53: {sampleData._53}");
            Console.WriteLine($"_54: {sampleData._54}");
            Console.WriteLine($"_55: {sampleData._55}");
            Console.WriteLine($"_56: {sampleData._56}");
            Console.WriteLine($"_57: {sampleData._57}");
            Console.WriteLine($"_58: {sampleData._58}");
            Console.WriteLine($"_59: {sampleData._59}");
            Console.WriteLine($"_60: {sampleData._60}");
            Console.WriteLine($"_61: {sampleData._61}");
            Console.WriteLine($"_62: {sampleData._62}");
            Console.WriteLine($"_63: {sampleData._63}");
            Console.WriteLine($"_64: {sampleData._64}");
            Console.WriteLine($"_65: {sampleData._65}");
            Console.WriteLine($"_66: {sampleData._66}");
            Console.WriteLine($"_67: {sampleData._67}");
            Console.WriteLine($"_68: {sampleData._68}");
            Console.WriteLine($"_69: {sampleData._69}");
            Console.WriteLine($"_70: {sampleData._70}");
            Console.WriteLine($"_71: {sampleData._71}");
            Console.WriteLine($"_72: {sampleData._72}");
            Console.WriteLine($"_73: {sampleData._73}");
            Console.WriteLine($"_74: {sampleData._74}");
            Console.WriteLine($"_75: {sampleData._75}");
            Console.WriteLine($"_76: {sampleData._76}");
            Console.WriteLine($"_77: {sampleData._77}");
            Console.WriteLine($"_78: {sampleData._78}");
            Console.WriteLine($"_79: {sampleData._79}");
            Console.WriteLine($"_80: {sampleData._80}");
            Console.WriteLine($"_81: {sampleData._81}");
            Console.WriteLine($"_82: {sampleData._82}");
            Console.WriteLine($"_83: {sampleData._83}");
            Console.WriteLine($"_84: {sampleData._84}");
            Console.WriteLine($"_85: {sampleData._85}");
            Console.WriteLine($"_86: {sampleData._86}");
            Console.WriteLine($"_87: {sampleData._87}");
            Console.WriteLine($"_88: {sampleData._88}");
            Console.WriteLine($"_89: {sampleData._89}");
            Console.WriteLine($"_90: {sampleData._90}");
            Console.WriteLine($"_91: {sampleData._91}");
            Console.WriteLine($"_92: {sampleData._92}");
            Console.WriteLine($"_93: {sampleData._93}");
            Console.WriteLine($"_94: {sampleData._94}");
            Console.WriteLine($"_95: {sampleData._95}");
            Console.WriteLine($"_96: {sampleData._96}");
            Console.WriteLine($"_97: {sampleData._97}");
            Console.WriteLine($"_98: {sampleData._98}");
            Console.WriteLine($"_99: {sampleData._99}");
            Console.WriteLine($"_100: {sampleData._100}");
            Console.WriteLine($"_101: {sampleData._101}");
            Console.WriteLine($"_102: {sampleData._102}");
            Console.WriteLine($"_103: {sampleData._103}");
            Console.WriteLine($"_104: {sampleData._104}");
            Console.WriteLine($"_105: {sampleData._105}");
            Console.WriteLine($"_106: {sampleData._106}");
            Console.WriteLine($"_107: {sampleData._107}");
            Console.WriteLine($"_108: {sampleData._108}");
            Console.WriteLine($"_109: {sampleData._109}");
            Console.WriteLine($"_110: {sampleData._110}");
            Console.WriteLine($"_111: {sampleData._111}");
            Console.WriteLine($"_112: {sampleData._112}");
            Console.WriteLine($"_113: {sampleData._113}");
            Console.WriteLine($"_114: {sampleData._114}");
            Console.WriteLine($"_115: {sampleData._115}");
            Console.WriteLine($"_116: {sampleData._116}");
            Console.WriteLine($"_117: {sampleData._117}");
            Console.WriteLine($"_118: {sampleData._118}");
            Console.WriteLine($"_119: {sampleData._119}");
            Console.WriteLine($"_120: {sampleData._120}");
            Console.WriteLine($"_121: {sampleData._121}");
            Console.WriteLine($"_122: {sampleData._122}");
            Console.WriteLine($"_123: {sampleData._123}");
            Console.WriteLine($"_124: {sampleData._124}");
            Console.WriteLine($"_125: {sampleData._125}");
            Console.WriteLine($"_126: {sampleData._126}");
            Console.WriteLine($"_127: {sampleData._127}");
            Console.WriteLine($"_128: {sampleData._128}");
            Console.WriteLine($"_129: {sampleData._129}");
            Console.WriteLine($"_130: {sampleData._130}");
            Console.WriteLine($"_131: {sampleData._131}");
            Console.WriteLine($"_132: {sampleData._132}");
            Console.WriteLine($"_133: {sampleData._133}");
            Console.WriteLine($"_134: {sampleData._134}");
            Console.WriteLine($"_135: {sampleData._135}");
            Console.WriteLine($"_136: {sampleData._136}");
            Console.WriteLine($"_137: {sampleData._137}");
            Console.WriteLine($"_138: {sampleData._138}");
            Console.WriteLine($"_139: {sampleData._139}");
            Console.WriteLine($"_140: {sampleData._140}");
            Console.WriteLine($"_141: {sampleData._141}");
            Console.WriteLine($"_142: {sampleData._142}");
            Console.WriteLine($"_143: {sampleData._143}");
            Console.WriteLine($"_144: {sampleData._144}");
            Console.WriteLine($"_145: {sampleData._145}");
            Console.WriteLine($"_146: {sampleData._146}");
            Console.WriteLine($"_147: {sampleData._147}");
            Console.WriteLine($"_148: {sampleData._148}");
            Console.WriteLine($"_149: {sampleData._149}");
            Console.WriteLine($"_150: {sampleData._150}");
            Console.WriteLine($"_151: {sampleData._151}");
            Console.WriteLine($"_152: {sampleData._152}");
            Console.WriteLine($"_153: {sampleData._153}");
            Console.WriteLine($"_154: {sampleData._154}");
            Console.WriteLine($"_155: {sampleData._155}");
            Console.WriteLine($"_156: {sampleData._156}");
            Console.WriteLine($"_157: {sampleData._157}");
            Console.WriteLine($"_158: {sampleData._158}");
            Console.WriteLine($"_159: {sampleData._159}");
            Console.WriteLine($"_160: {sampleData._160}");
            Console.WriteLine($"_161: {sampleData._161}");
            Console.WriteLine($"_162: {sampleData._162}");
            Console.WriteLine($"_163: {sampleData._163}");
            Console.WriteLine($"_164: {sampleData._164}");
            Console.WriteLine($"_165: {sampleData._165}");
            Console.WriteLine($"_166: {sampleData._166}");
            Console.WriteLine($"_167: {sampleData._167}");
            Console.WriteLine($"_168: {sampleData._168}");
            Console.WriteLine($"_169: {sampleData._169}");
            Console.WriteLine($"_170: {sampleData._170}");
            Console.WriteLine($"_171: {sampleData._171}");
            Console.WriteLine($"_172: {sampleData._172}");
            Console.WriteLine($"_173: {sampleData._173}");
            Console.WriteLine($"_174: {sampleData._174}");
            Console.WriteLine($"_175: {sampleData._175}");
            Console.WriteLine($"_176: {sampleData._176}");
            Console.WriteLine($"_177: {sampleData._177}");
            Console.WriteLine($"_178: {sampleData._178}");
            Console.WriteLine($"_179: {sampleData._179}");
            Console.WriteLine($"_180: {sampleData._180}");
            Console.WriteLine($"_181: {sampleData._181}");
            Console.WriteLine($"_182: {sampleData._182}");
            Console.WriteLine($"_183: {sampleData._183}");
            Console.WriteLine($"_184: {sampleData._184}");
            Console.WriteLine($"_185: {sampleData._185}");
            Console.WriteLine($"_186: {sampleData._186}");
            Console.WriteLine($"_187: {sampleData._187}");
            Console.WriteLine($"_188: {sampleData._188}");
            Console.WriteLine($"_189: {sampleData._189}");
            Console.WriteLine($"_190: {sampleData._190}");
            Console.WriteLine($"_191: {sampleData._191}");
            Console.WriteLine($"_192: {sampleData._192}");
            Console.WriteLine($"_193: {sampleData._193}");
            Console.WriteLine($"_194: {sampleData._194}");
            Console.WriteLine($"_195: {sampleData._195}");
            Console.WriteLine($"_196: {sampleData._196}");
            Console.WriteLine($"_197: {sampleData._197}");
            Console.WriteLine($"_198: {sampleData._198}");
            Console.WriteLine($"_199: {sampleData._199}");
            Console.WriteLine($"_200: {sampleData._200}");
            Console.WriteLine($"_201: {sampleData._201}");
            Console.WriteLine($"_202: {sampleData._202}");
            Console.WriteLine($"_203: {sampleData._203}");
            Console.WriteLine($"_204: {sampleData._204}");
            Console.WriteLine($"_205: {sampleData._205}");
            Console.WriteLine($"_206: {sampleData._206}");
            Console.WriteLine($"_207: {sampleData._207}");
            Console.WriteLine($"_208: {sampleData._208}");
            Console.WriteLine($"_209: {sampleData._209}");
            Console.WriteLine($"_210: {sampleData._210}");
            Console.WriteLine($"_211: {sampleData._211}");
            Console.WriteLine($"_212: {sampleData._212}");
            Console.WriteLine($"_213: {sampleData._213}");
            Console.WriteLine($"_214: {sampleData._214}");
            Console.WriteLine($"_215: {sampleData._215}");
            Console.WriteLine($"_216: {sampleData._216}");
            Console.WriteLine($"_217: {sampleData._217}");
            Console.WriteLine($"_218: {sampleData._218}");
            Console.WriteLine($"_219: {sampleData._219}");
            Console.WriteLine($"_220: {sampleData._220}");
            Console.WriteLine($"_221: {sampleData._221}");
            Console.WriteLine($"_222: {sampleData._222}");
            Console.WriteLine($"_223: {sampleData._223}");
            Console.WriteLine($"_224: {sampleData._224}");
            Console.WriteLine($"_225: {sampleData._225}");
            Console.WriteLine($"_226: {sampleData._226}");
            Console.WriteLine($"_227: {sampleData._227}");
            Console.WriteLine($"_228: {sampleData._228}");
            Console.WriteLine($"_229: {sampleData._229}");
            Console.WriteLine($"_230: {sampleData._230}");
            Console.WriteLine($"_231: {sampleData._231}");
            Console.WriteLine($"_232: {sampleData._232}");
            Console.WriteLine($"_233: {sampleData._233}");
            Console.WriteLine($"_234: {sampleData._234}");
            Console.WriteLine($"_235: {sampleData._235}");
            Console.WriteLine($"_236: {sampleData._236}");
            Console.WriteLine($"_237: {sampleData._237}");
            Console.WriteLine($"_238: {sampleData._238}");
            Console.WriteLine($"_239: {sampleData._239}");
            Console.WriteLine($"_240: {sampleData._240}");
            Console.WriteLine($"_241: {sampleData._241}");
            Console.WriteLine($"_242: {sampleData._242}");
            Console.WriteLine($"_243: {sampleData._243}");
            Console.WriteLine($"_244: {sampleData._244}");
            Console.WriteLine($"_245: {sampleData._245}");
            Console.WriteLine($"_246: {sampleData._246}");
            Console.WriteLine($"_247: {sampleData._247}");
            Console.WriteLine($"_248: {sampleData._248}");
            Console.WriteLine($"_249: {sampleData._249}");
            Console.WriteLine($"_250: {sampleData._250}");
            Console.WriteLine($"_251: {sampleData._251}");
            Console.WriteLine($"_252: {sampleData._252}");
            Console.WriteLine($"_253: {sampleData._253}");
            Console.WriteLine($"_254: {sampleData._254}");
            Console.WriteLine($"_255: {sampleData._255}");
            Console.WriteLine($"_256: {sampleData._256}");
            Console.WriteLine($"_257: {sampleData._257}");
            Console.WriteLine($"_258: {sampleData._258}");
            Console.WriteLine($"_259: {sampleData._259}");
            Console.WriteLine($"_260: {sampleData._260}");
            Console.WriteLine($"_261: {sampleData._261}");
            Console.WriteLine($"_262: {sampleData._262}");
            Console.WriteLine($"_263: {sampleData._263}");
            Console.WriteLine($"_264: {sampleData._264}");
            Console.WriteLine($"_265: {sampleData._265}");
            Console.WriteLine($"_266: {sampleData._266}");
            Console.WriteLine($"_267: {sampleData._267}");
            Console.WriteLine($"_268: {sampleData._268}");
            Console.WriteLine($"_269: {sampleData._269}");
            Console.WriteLine($"_270: {sampleData._270}");
            Console.WriteLine($"_271: {sampleData._271}");
            Console.WriteLine($"_272: {sampleData._272}");
            Console.WriteLine($"_273: {sampleData._273}");
            Console.WriteLine($"_274: {sampleData._274}");
            Console.WriteLine($"_275: {sampleData._275}");
            Console.WriteLine($"_276: {sampleData._276}");
            Console.WriteLine($"_277: {sampleData._277}");
            Console.WriteLine($"_278: {sampleData._278}");
            Console.WriteLine($"_279: {sampleData._279}");
            Console.WriteLine($"_280: {sampleData._280}");
            Console.WriteLine($"_281: {sampleData._281}");
            Console.WriteLine($"_282: {sampleData._282}");
            Console.WriteLine($"_283: {sampleData._283}");
            Console.WriteLine($"_284: {sampleData._284}");
            Console.WriteLine($"_285: {sampleData._285}");
            Console.WriteLine($"_286: {sampleData._286}");
            Console.WriteLine($"_287: {sampleData._287}");
            Console.WriteLine($"_288: {sampleData._288}");
            Console.WriteLine($"_289: {sampleData._289}");
            Console.WriteLine($"_290: {sampleData._290}");
            Console.WriteLine($"_291: {sampleData._291}");
            Console.WriteLine($"_292: {sampleData._292}");
            Console.WriteLine($"_293: {sampleData._293}");
            Console.WriteLine($"_294: {sampleData._294}");
            Console.WriteLine($"_295: {sampleData._295}");
            Console.WriteLine($"_296: {sampleData._296}");
            Console.WriteLine($"_297: {sampleData._297}");
            Console.WriteLine($"_298: {sampleData._298}");
            Console.WriteLine($"_299: {sampleData._299}");
            Console.WriteLine($"_300: {sampleData._300}");
            Console.WriteLine($"_301: {sampleData._301}");
            Console.WriteLine($"_302: {sampleData._302}");
            Console.WriteLine($"_303: {sampleData._303}");
            Console.WriteLine($"_304: {sampleData._304}");
            Console.WriteLine($"_305: {sampleData._305}");
            Console.WriteLine($"_306: {sampleData._306}");
            Console.WriteLine($"_307: {sampleData._307}");
            Console.WriteLine($"_308: {sampleData._308}");
            Console.WriteLine($"_309: {sampleData._309}");
            Console.WriteLine($"_310: {sampleData._310}");
            Console.WriteLine($"_311: {sampleData._311}");
            Console.WriteLine($"_312: {sampleData._312}");
            Console.WriteLine($"_313: {sampleData._313}");
            Console.WriteLine($"_314: {sampleData._314}");
            Console.WriteLine($"_315: {sampleData._315}");
            Console.WriteLine($"_316: {sampleData._316}");
            Console.WriteLine($"_317: {sampleData._317}");
            Console.WriteLine($"_318: {sampleData._318}");
            Console.WriteLine($"_319: {sampleData._319}");
            Console.WriteLine($"_320: {sampleData._320}");
            Console.WriteLine($"_321: {sampleData._321}");
            Console.WriteLine($"_322: {sampleData._322}");
            Console.WriteLine($"_323: {sampleData._323}");
            Console.WriteLine($"_324: {sampleData._324}");
            Console.WriteLine($"_325: {sampleData._325}");
            Console.WriteLine($"_326: {sampleData._326}");
            Console.WriteLine($"_327: {sampleData._327}");
            Console.WriteLine($"_328: {sampleData._328}");
            Console.WriteLine($"_329: {sampleData._329}");
            Console.WriteLine($"_330: {sampleData._330}");
            Console.WriteLine($"_331: {sampleData._331}");
            Console.WriteLine($"_332: {sampleData._332}");
            Console.WriteLine($"_333: {sampleData._333}");
            Console.WriteLine($"_334: {sampleData._334}");
            Console.WriteLine($"_335: {sampleData._335}");
            Console.WriteLine($"_336: {sampleData._336}");
            Console.WriteLine($"_337: {sampleData._337}");
            Console.WriteLine($"_338: {sampleData._338}");
            Console.WriteLine($"_339: {sampleData._339}");
            Console.WriteLine($"_340: {sampleData._340}");
            Console.WriteLine($"_341: {sampleData._341}");
            Console.WriteLine($"_342: {sampleData._342}");
            Console.WriteLine($"_343: {sampleData._343}");
            Console.WriteLine($"_344: {sampleData._344}");
            Console.WriteLine($"_345: {sampleData._345}");
            Console.WriteLine($"_346: {sampleData._346}");
            Console.WriteLine($"_347: {sampleData._347}");
            Console.WriteLine($"_348: {sampleData._348}");
            Console.WriteLine($"_349: {sampleData._349}");
            Console.WriteLine($"_350: {sampleData._350}");
            Console.WriteLine($"_351: {sampleData._351}");
            Console.WriteLine($"_352: {sampleData._352}");
            Console.WriteLine($"_353: {sampleData._353}");
            Console.WriteLine($"_354: {sampleData._354}");
            Console.WriteLine($"_355: {sampleData._355}");
            Console.WriteLine($"_356: {sampleData._356}");
            Console.WriteLine($"_357: {sampleData._357}");
            Console.WriteLine($"_358: {sampleData._358}");
            Console.WriteLine($"_359: {sampleData._359}");
            Console.WriteLine($"_360: {sampleData._360}");
            Console.WriteLine($"_361: {sampleData._361}");
            Console.WriteLine($"_362: {sampleData._362}");
            Console.WriteLine($"_363: {sampleData._363}");
            Console.WriteLine($"_364: {sampleData._364}");
            Console.WriteLine($"_365: {sampleData._365}");
            Console.WriteLine($"_366: {sampleData._366}");
            Console.WriteLine($"_367: {sampleData._367}");
            Console.WriteLine($"_368: {sampleData._368}");
            Console.WriteLine($"_369: {sampleData._369}");
            Console.WriteLine($"_370: {sampleData._370}");
            Console.WriteLine($"_371: {sampleData._371}");
            Console.WriteLine($"_372: {sampleData._372}");
            Console.WriteLine($"_373: {sampleData._373}");
            Console.WriteLine($"_374: {sampleData._374}");
            Console.WriteLine($"_375: {sampleData._375}");
            Console.WriteLine($"_376: {sampleData._376}");
            Console.WriteLine($"_377: {sampleData._377}");
            Console.WriteLine($"_378: {sampleData._378}");
            Console.WriteLine($"_379: {sampleData._379}");
            Console.WriteLine($"_380: {sampleData._380}");
            Console.WriteLine($"_381: {sampleData._381}");
            Console.WriteLine($"_382: {sampleData._382}");
            Console.WriteLine($"_383: {sampleData._383}");
            Console.WriteLine($"_384: {sampleData._384}");
            Console.WriteLine($"_385: {sampleData._385}");
            Console.WriteLine($"_386: {sampleData._386}");
            Console.WriteLine($"_387: {sampleData._387}");
            Console.WriteLine($"_388: {sampleData._388}");
            Console.WriteLine($"_389: {sampleData._389}");
            Console.WriteLine($"_390: {sampleData._390}");
            Console.WriteLine($"_391: {sampleData._391}");
            Console.WriteLine($"_392: {sampleData._392}");
            Console.WriteLine($"_393: {sampleData._393}");
            Console.WriteLine($"_394: {sampleData._394}");
            Console.WriteLine($"_395: {sampleData._395}");
            Console.WriteLine($"_396: {sampleData._396}");
            Console.WriteLine($"_397: {sampleData._397}");
            Console.WriteLine($"_398: {sampleData._398}");
            Console.WriteLine($"_399: {sampleData._399}");
            Console.WriteLine($"_400: {sampleData._400}");
            Console.WriteLine($"_401: {sampleData._401}");
            Console.WriteLine($"_402: {sampleData._402}");
            Console.WriteLine($"_403: {sampleData._403}");
            Console.WriteLine($"_404: {sampleData._404}");
            Console.WriteLine($"_405: {sampleData._405}");
            Console.WriteLine($"_406: {sampleData._406}");
            Console.WriteLine($"_407: {sampleData._407}");
            Console.WriteLine($"_408: {sampleData._408}");
            Console.WriteLine($"_409: {sampleData._409}");
            Console.WriteLine($"_410: {sampleData._410}");
            Console.WriteLine($"_411: {sampleData._411}");
            Console.WriteLine($"_412: {sampleData._412}");
            Console.WriteLine($"_413: {sampleData._413}");
            Console.WriteLine($"_414: {sampleData._414}");
            Console.WriteLine($"_415: {sampleData._415}");
            Console.WriteLine($"_416: {sampleData._416}");
            Console.WriteLine($"_417: {sampleData._417}");
            Console.WriteLine($"_418: {sampleData._418}");
            Console.WriteLine($"_419: {sampleData._419}");
            Console.WriteLine($"_420: {sampleData._420}");
            Console.WriteLine($"_421: {sampleData._421}");
            Console.WriteLine($"_422: {sampleData._422}");
            Console.WriteLine($"_423: {sampleData._423}");
            Console.WriteLine($"_424: {sampleData._424}");
            Console.WriteLine($"_425: {sampleData._425}");
            Console.WriteLine($"_426: {sampleData._426}");
            Console.WriteLine($"_427: {sampleData._427}");
            Console.WriteLine($"_428: {sampleData._428}");
            Console.WriteLine($"_429: {sampleData._429}");
            Console.WriteLine($"_430: {sampleData._430}");
            Console.WriteLine($"_431: {sampleData._431}");
            Console.WriteLine($"_432: {sampleData._432}");
            Console.WriteLine($"_433: {sampleData._433}");
            Console.WriteLine($"_434: {sampleData._434}");
            Console.WriteLine($"_435: {sampleData._435}");
            Console.WriteLine($"_436: {sampleData._436}");
            Console.WriteLine($"_437: {sampleData._437}");
            Console.WriteLine($"_438: {sampleData._438}");
            Console.WriteLine($"_439: {sampleData._439}");
            Console.WriteLine($"_440: {sampleData._440}");
            Console.WriteLine($"_441: {sampleData._441}");
            Console.WriteLine($"_442: {sampleData._442}");
            Console.WriteLine($"_443: {sampleData._443}");
            Console.WriteLine($"_444: {sampleData._444}");
            Console.WriteLine($"_445: {sampleData._445}");
            Console.WriteLine($"_446: {sampleData._446}");
            Console.WriteLine($"_447: {sampleData._447}");
            Console.WriteLine($"_448: {sampleData._448}");
            Console.WriteLine($"_449: {sampleData._449}");
            Console.WriteLine($"_450: {sampleData._450}");
            Console.WriteLine($"_451: {sampleData._451}");
            Console.WriteLine($"_452: {sampleData._452}");
            Console.WriteLine($"_453: {sampleData._453}");
            Console.WriteLine($"_454: {sampleData._454}");
            Console.WriteLine($"_455: {sampleData._455}");
            Console.WriteLine($"_456: {sampleData._456}");
            Console.WriteLine($"_457: {sampleData._457}");
            Console.WriteLine($"_458: {sampleData._458}");
            Console.WriteLine($"_459: {sampleData._459}");
            Console.WriteLine($"_460: {sampleData._460}");
            Console.WriteLine($"_461: {sampleData._461}");
            Console.WriteLine($"_462: {sampleData._462}");
            Console.WriteLine($"_463: {sampleData._463}");
            Console.WriteLine($"_464: {sampleData._464}");
            Console.WriteLine($"_465: {sampleData._465}");
            Console.WriteLine($"_466: {sampleData._466}");
            Console.WriteLine($"_467: {sampleData._467}");
            Console.WriteLine($"_468: {sampleData._468}");
            Console.WriteLine($"_469: {sampleData._469}");
            Console.WriteLine($"_470: {sampleData._470}");
            Console.WriteLine($"_471: {sampleData._471}");
            Console.WriteLine($"_472: {sampleData._472}");
            Console.WriteLine($"_473: {sampleData._473}");
            Console.WriteLine($"_474: {sampleData._474}");
            Console.WriteLine($"_475: {sampleData._475}");
            Console.WriteLine($"_476: {sampleData._476}");
            Console.WriteLine($"_477: {sampleData._477}");
            Console.WriteLine($"_478: {sampleData._478}");
            Console.WriteLine($"_479: {sampleData._479}");
            Console.WriteLine($"\n\nPredicted Target value {predictionResult.Prediction} \nPredicted Target scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
