// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Kinect_Science_FairML.Model
{
    public class ModelInput
    {
        [ColumnName("Target"), LoadColumn(0)]
        public string Target { get; set; }


        [ColumnName("0"), LoadColumn(1)]
        public float _0 { get; set; }


        [ColumnName("1"), LoadColumn(2)]
        public float _1 { get; set; }


        [ColumnName("2"), LoadColumn(3)]
        public float _2 { get; set; }


        [ColumnName("3"), LoadColumn(4)]
        public float _3 { get; set; }


        [ColumnName("4"), LoadColumn(5)]
        public float _4 { get; set; }


        [ColumnName("5"), LoadColumn(6)]
        public float _5 { get; set; }


        [ColumnName("6"), LoadColumn(7)]
        public float _6 { get; set; }


        [ColumnName("7"), LoadColumn(8)]
        public float _7 { get; set; }


        [ColumnName("8"), LoadColumn(9)]
        public float _8 { get; set; }


        [ColumnName("9"), LoadColumn(10)]
        public float _9 { get; set; }


        [ColumnName("10"), LoadColumn(11)]
        public float _10 { get; set; }


        [ColumnName("11"), LoadColumn(12)]
        public float _11 { get; set; }


        [ColumnName("12"), LoadColumn(13)]
        public float _12 { get; set; }


        [ColumnName("13"), LoadColumn(14)]
        public float _13 { get; set; }


        [ColumnName("14"), LoadColumn(15)]
        public float _14 { get; set; }


        [ColumnName("15"), LoadColumn(16)]
        public float _15 { get; set; }


        [ColumnName("16"), LoadColumn(17)]
        public float _16 { get; set; }


        [ColumnName("17"), LoadColumn(18)]
        public float _17 { get; set; }


        [ColumnName("18"), LoadColumn(19)]
        public float _18 { get; set; }


        [ColumnName("19"), LoadColumn(20)]
        public float _19 { get; set; }


        [ColumnName("20"), LoadColumn(21)]
        public float _20 { get; set; }


        [ColumnName("21"), LoadColumn(22)]
        public float _21 { get; set; }


        [ColumnName("22"), LoadColumn(23)]
        public float _22 { get; set; }


        [ColumnName("23"), LoadColumn(24)]
        public float _23 { get; set; }


        [ColumnName("24"), LoadColumn(25)]
        public float _24 { get; set; }


        [ColumnName("25"), LoadColumn(26)]
        public float _25 { get; set; }


        [ColumnName("26"), LoadColumn(27)]
        public float _26 { get; set; }


        [ColumnName("27"), LoadColumn(28)]
        public float _27 { get; set; }


        [ColumnName("28"), LoadColumn(29)]
        public float _28 { get; set; }


        [ColumnName("29"), LoadColumn(30)]
        public float _29 { get; set; }


        [ColumnName("30"), LoadColumn(31)]
        public float _30 { get; set; }


        [ColumnName("31"), LoadColumn(32)]
        public float _31 { get; set; }


        [ColumnName("32"), LoadColumn(33)]
        public float _32 { get; set; }


        [ColumnName("33"), LoadColumn(34)]
        public float _33 { get; set; }


        [ColumnName("34"), LoadColumn(35)]
        public float _34 { get; set; }


        [ColumnName("35"), LoadColumn(36)]
        public float _35 { get; set; }


        [ColumnName("36"), LoadColumn(37)]
        public float _36 { get; set; }


        [ColumnName("37"), LoadColumn(38)]
        public float _37 { get; set; }


        [ColumnName("38"), LoadColumn(39)]
        public float _38 { get; set; }


        [ColumnName("39"), LoadColumn(40)]
        public float _39 { get; set; }


        [ColumnName("40"), LoadColumn(41)]
        public float _40 { get; set; }


        [ColumnName("41"), LoadColumn(42)]
        public float _41 { get; set; }


        [ColumnName("42"), LoadColumn(43)]
        public float _42 { get; set; }


        [ColumnName("43"), LoadColumn(44)]
        public float _43 { get; set; }


        [ColumnName("44"), LoadColumn(45)]
        public float _44 { get; set; }


        [ColumnName("45"), LoadColumn(46)]
        public float _45 { get; set; }


        [ColumnName("46"), LoadColumn(47)]
        public float _46 { get; set; }


        [ColumnName("47"), LoadColumn(48)]
        public float _47 { get; set; }


        [ColumnName("48"), LoadColumn(49)]
        public float _48 { get; set; }


        [ColumnName("49"), LoadColumn(50)]
        public float _49 { get; set; }


        [ColumnName("50"), LoadColumn(51)]
        public float _50 { get; set; }


        [ColumnName("51"), LoadColumn(52)]
        public float _51 { get; set; }


        [ColumnName("52"), LoadColumn(53)]
        public float _52 { get; set; }


        [ColumnName("53"), LoadColumn(54)]
        public float _53 { get; set; }


        [ColumnName("54"), LoadColumn(55)]
        public float _54 { get; set; }


        [ColumnName("55"), LoadColumn(56)]
        public float _55 { get; set; }


        [ColumnName("56"), LoadColumn(57)]
        public float _56 { get; set; }


        [ColumnName("57"), LoadColumn(58)]
        public float _57 { get; set; }


        [ColumnName("58"), LoadColumn(59)]
        public float _58 { get; set; }


        [ColumnName("59"), LoadColumn(60)]
        public float _59 { get; set; }


        [ColumnName("60"), LoadColumn(61)]
        public float _60 { get; set; }


        [ColumnName("61"), LoadColumn(62)]
        public float _61 { get; set; }


        [ColumnName("62"), LoadColumn(63)]
        public float _62 { get; set; }


        [ColumnName("63"), LoadColumn(64)]
        public float _63 { get; set; }


        [ColumnName("64"), LoadColumn(65)]
        public float _64 { get; set; }


        [ColumnName("65"), LoadColumn(66)]
        public float _65 { get; set; }


        [ColumnName("66"), LoadColumn(67)]
        public float _66 { get; set; }


        [ColumnName("67"), LoadColumn(68)]
        public float _67 { get; set; }


        [ColumnName("68"), LoadColumn(69)]
        public float _68 { get; set; }


        [ColumnName("69"), LoadColumn(70)]
        public float _69 { get; set; }


        [ColumnName("70"), LoadColumn(71)]
        public float _70 { get; set; }


        [ColumnName("71"), LoadColumn(72)]
        public float _71 { get; set; }


        [ColumnName("72"), LoadColumn(73)]
        public float _72 { get; set; }


        [ColumnName("73"), LoadColumn(74)]
        public float _73 { get; set; }


        [ColumnName("74"), LoadColumn(75)]
        public float _74 { get; set; }


        [ColumnName("75"), LoadColumn(76)]
        public float _75 { get; set; }


        [ColumnName("76"), LoadColumn(77)]
        public float _76 { get; set; }


        [ColumnName("77"), LoadColumn(78)]
        public float _77 { get; set; }


        [ColumnName("78"), LoadColumn(79)]
        public float _78 { get; set; }


        [ColumnName("79"), LoadColumn(80)]
        public float _79 { get; set; }


        [ColumnName("80"), LoadColumn(81)]
        public float _80 { get; set; }


        [ColumnName("81"), LoadColumn(82)]
        public float _81 { get; set; }


        [ColumnName("82"), LoadColumn(83)]
        public float _82 { get; set; }


        [ColumnName("83"), LoadColumn(84)]
        public float _83 { get; set; }


        [ColumnName("84"), LoadColumn(85)]
        public float _84 { get; set; }


        [ColumnName("85"), LoadColumn(86)]
        public float _85 { get; set; }


        [ColumnName("86"), LoadColumn(87)]
        public float _86 { get; set; }


        [ColumnName("87"), LoadColumn(88)]
        public float _87 { get; set; }


        [ColumnName("88"), LoadColumn(89)]
        public float _88 { get; set; }


        [ColumnName("89"), LoadColumn(90)]
        public float _89 { get; set; }


        [ColumnName("90"), LoadColumn(91)]
        public float _90 { get; set; }


        [ColumnName("91"), LoadColumn(92)]
        public float _91 { get; set; }


        [ColumnName("92"), LoadColumn(93)]
        public float _92 { get; set; }


        [ColumnName("93"), LoadColumn(94)]
        public float _93 { get; set; }


        [ColumnName("94"), LoadColumn(95)]
        public float _94 { get; set; }


        [ColumnName("95"), LoadColumn(96)]
        public float _95 { get; set; }


        [ColumnName("96"), LoadColumn(97)]
        public float _96 { get; set; }


        [ColumnName("97"), LoadColumn(98)]
        public float _97 { get; set; }


        [ColumnName("98"), LoadColumn(99)]
        public float _98 { get; set; }


        [ColumnName("99"), LoadColumn(100)]
        public float _99 { get; set; }


        [ColumnName("100"), LoadColumn(101)]
        public float _100 { get; set; }


        [ColumnName("101"), LoadColumn(102)]
        public float _101 { get; set; }


        [ColumnName("102"), LoadColumn(103)]
        public float _102 { get; set; }


        [ColumnName("103"), LoadColumn(104)]
        public float _103 { get; set; }


        [ColumnName("104"), LoadColumn(105)]
        public float _104 { get; set; }


        [ColumnName("105"), LoadColumn(106)]
        public float _105 { get; set; }


        [ColumnName("106"), LoadColumn(107)]
        public float _106 { get; set; }


        [ColumnName("107"), LoadColumn(108)]
        public float _107 { get; set; }


        [ColumnName("108"), LoadColumn(109)]
        public float _108 { get; set; }


        [ColumnName("109"), LoadColumn(110)]
        public float _109 { get; set; }


        [ColumnName("110"), LoadColumn(111)]
        public float _110 { get; set; }


        [ColumnName("111"), LoadColumn(112)]
        public float _111 { get; set; }


        [ColumnName("112"), LoadColumn(113)]
        public float _112 { get; set; }


        [ColumnName("113"), LoadColumn(114)]
        public float _113 { get; set; }


        [ColumnName("114"), LoadColumn(115)]
        public float _114 { get; set; }


        [ColumnName("115"), LoadColumn(116)]
        public float _115 { get; set; }


        [ColumnName("116"), LoadColumn(117)]
        public float _116 { get; set; }


        [ColumnName("117"), LoadColumn(118)]
        public float _117 { get; set; }


        [ColumnName("118"), LoadColumn(119)]
        public float _118 { get; set; }


        [ColumnName("119"), LoadColumn(120)]
        public float _119 { get; set; }


        [ColumnName("120"), LoadColumn(121)]
        public float _120 { get; set; }


        [ColumnName("121"), LoadColumn(122)]
        public float _121 { get; set; }


        [ColumnName("122"), LoadColumn(123)]
        public float _122 { get; set; }


        [ColumnName("123"), LoadColumn(124)]
        public float _123 { get; set; }


        [ColumnName("124"), LoadColumn(125)]
        public float _124 { get; set; }


        [ColumnName("125"), LoadColumn(126)]
        public float _125 { get; set; }


        [ColumnName("126"), LoadColumn(127)]
        public float _126 { get; set; }


        [ColumnName("127"), LoadColumn(128)]
        public float _127 { get; set; }


        [ColumnName("128"), LoadColumn(129)]
        public float _128 { get; set; }


        [ColumnName("129"), LoadColumn(130)]
        public float _129 { get; set; }


        [ColumnName("130"), LoadColumn(131)]
        public float _130 { get; set; }


        [ColumnName("131"), LoadColumn(132)]
        public float _131 { get; set; }


        [ColumnName("132"), LoadColumn(133)]
        public float _132 { get; set; }


        [ColumnName("133"), LoadColumn(134)]
        public float _133 { get; set; }


        [ColumnName("134"), LoadColumn(135)]
        public float _134 { get; set; }


        [ColumnName("135"), LoadColumn(136)]
        public float _135 { get; set; }


        [ColumnName("136"), LoadColumn(137)]
        public float _136 { get; set; }


        [ColumnName("137"), LoadColumn(138)]
        public float _137 { get; set; }


        [ColumnName("138"), LoadColumn(139)]
        public float _138 { get; set; }


        [ColumnName("139"), LoadColumn(140)]
        public float _139 { get; set; }


        [ColumnName("140"), LoadColumn(141)]
        public float _140 { get; set; }


        [ColumnName("141"), LoadColumn(142)]
        public float _141 { get; set; }


        [ColumnName("142"), LoadColumn(143)]
        public float _142 { get; set; }


        [ColumnName("143"), LoadColumn(144)]
        public float _143 { get; set; }


        [ColumnName("144"), LoadColumn(145)]
        public float _144 { get; set; }


        [ColumnName("145"), LoadColumn(146)]
        public float _145 { get; set; }


        [ColumnName("146"), LoadColumn(147)]
        public float _146 { get; set; }


        [ColumnName("147"), LoadColumn(148)]
        public float _147 { get; set; }


        [ColumnName("148"), LoadColumn(149)]
        public float _148 { get; set; }


        [ColumnName("149"), LoadColumn(150)]
        public float _149 { get; set; }


        [ColumnName("150"), LoadColumn(151)]
        public float _150 { get; set; }


        [ColumnName("151"), LoadColumn(152)]
        public float _151 { get; set; }


        [ColumnName("152"), LoadColumn(153)]
        public float _152 { get; set; }


        [ColumnName("153"), LoadColumn(154)]
        public float _153 { get; set; }


        [ColumnName("154"), LoadColumn(155)]
        public float _154 { get; set; }


        [ColumnName("155"), LoadColumn(156)]
        public float _155 { get; set; }


        [ColumnName("156"), LoadColumn(157)]
        public float _156 { get; set; }


        [ColumnName("157"), LoadColumn(158)]
        public float _157 { get; set; }


        [ColumnName("158"), LoadColumn(159)]
        public float _158 { get; set; }


        [ColumnName("159"), LoadColumn(160)]
        public float _159 { get; set; }


        [ColumnName("160"), LoadColumn(161)]
        public float _160 { get; set; }


        [ColumnName("161"), LoadColumn(162)]
        public float _161 { get; set; }


        [ColumnName("162"), LoadColumn(163)]
        public float _162 { get; set; }


        [ColumnName("163"), LoadColumn(164)]
        public float _163 { get; set; }


        [ColumnName("164"), LoadColumn(165)]
        public float _164 { get; set; }


        [ColumnName("165"), LoadColumn(166)]
        public float _165 { get; set; }


        [ColumnName("166"), LoadColumn(167)]
        public float _166 { get; set; }


        [ColumnName("167"), LoadColumn(168)]
        public float _167 { get; set; }


        [ColumnName("168"), LoadColumn(169)]
        public float _168 { get; set; }


        [ColumnName("169"), LoadColumn(170)]
        public float _169 { get; set; }


        [ColumnName("170"), LoadColumn(171)]
        public float _170 { get; set; }


        [ColumnName("171"), LoadColumn(172)]
        public float _171 { get; set; }


        [ColumnName("172"), LoadColumn(173)]
        public float _172 { get; set; }


        [ColumnName("173"), LoadColumn(174)]
        public float _173 { get; set; }


        [ColumnName("174"), LoadColumn(175)]
        public float _174 { get; set; }


        [ColumnName("175"), LoadColumn(176)]
        public float _175 { get; set; }


        [ColumnName("176"), LoadColumn(177)]
        public float _176 { get; set; }


        [ColumnName("177"), LoadColumn(178)]
        public float _177 { get; set; }


        [ColumnName("178"), LoadColumn(179)]
        public float _178 { get; set; }


        [ColumnName("179"), LoadColumn(180)]
        public float _179 { get; set; }


        [ColumnName("180"), LoadColumn(181)]
        public float _180 { get; set; }


        [ColumnName("181"), LoadColumn(182)]
        public float _181 { get; set; }


        [ColumnName("182"), LoadColumn(183)]
        public float _182 { get; set; }


        [ColumnName("183"), LoadColumn(184)]
        public float _183 { get; set; }


        [ColumnName("184"), LoadColumn(185)]
        public float _184 { get; set; }


        [ColumnName("185"), LoadColumn(186)]
        public float _185 { get; set; }


        [ColumnName("186"), LoadColumn(187)]
        public float _186 { get; set; }


        [ColumnName("187"), LoadColumn(188)]
        public float _187 { get; set; }


        [ColumnName("188"), LoadColumn(189)]
        public float _188 { get; set; }


        [ColumnName("189"), LoadColumn(190)]
        public float _189 { get; set; }


        [ColumnName("190"), LoadColumn(191)]
        public float _190 { get; set; }


        [ColumnName("191"), LoadColumn(192)]
        public float _191 { get; set; }


        [ColumnName("192"), LoadColumn(193)]
        public float _192 { get; set; }


        [ColumnName("193"), LoadColumn(194)]
        public float _193 { get; set; }


        [ColumnName("194"), LoadColumn(195)]
        public float _194 { get; set; }


        [ColumnName("195"), LoadColumn(196)]
        public float _195 { get; set; }


        [ColumnName("196"), LoadColumn(197)]
        public float _196 { get; set; }


        [ColumnName("197"), LoadColumn(198)]
        public float _197 { get; set; }


        [ColumnName("198"), LoadColumn(199)]
        public float _198 { get; set; }


        [ColumnName("199"), LoadColumn(200)]
        public float _199 { get; set; }


        [ColumnName("200"), LoadColumn(201)]
        public float _200 { get; set; }


        [ColumnName("201"), LoadColumn(202)]
        public float _201 { get; set; }


        [ColumnName("202"), LoadColumn(203)]
        public float _202 { get; set; }


        [ColumnName("203"), LoadColumn(204)]
        public float _203 { get; set; }


        [ColumnName("204"), LoadColumn(205)]
        public float _204 { get; set; }


        [ColumnName("205"), LoadColumn(206)]
        public float _205 { get; set; }


        [ColumnName("206"), LoadColumn(207)]
        public float _206 { get; set; }


        [ColumnName("207"), LoadColumn(208)]
        public float _207 { get; set; }


        [ColumnName("208"), LoadColumn(209)]
        public float _208 { get; set; }


        [ColumnName("209"), LoadColumn(210)]
        public float _209 { get; set; }


        [ColumnName("210"), LoadColumn(211)]
        public float _210 { get; set; }


        [ColumnName("211"), LoadColumn(212)]
        public float _211 { get; set; }


        [ColumnName("212"), LoadColumn(213)]
        public float _212 { get; set; }


        [ColumnName("213"), LoadColumn(214)]
        public float _213 { get; set; }


        [ColumnName("214"), LoadColumn(215)]
        public float _214 { get; set; }


        [ColumnName("215"), LoadColumn(216)]
        public float _215 { get; set; }


        [ColumnName("216"), LoadColumn(217)]
        public float _216 { get; set; }


        [ColumnName("217"), LoadColumn(218)]
        public float _217 { get; set; }


        [ColumnName("218"), LoadColumn(219)]
        public float _218 { get; set; }


        [ColumnName("219"), LoadColumn(220)]
        public float _219 { get; set; }


        [ColumnName("220"), LoadColumn(221)]
        public float _220 { get; set; }


        [ColumnName("221"), LoadColumn(222)]
        public float _221 { get; set; }


        [ColumnName("222"), LoadColumn(223)]
        public float _222 { get; set; }


        [ColumnName("223"), LoadColumn(224)]
        public float _223 { get; set; }


        [ColumnName("224"), LoadColumn(225)]
        public float _224 { get; set; }


        [ColumnName("225"), LoadColumn(226)]
        public float _225 { get; set; }


        [ColumnName("226"), LoadColumn(227)]
        public float _226 { get; set; }


        [ColumnName("227"), LoadColumn(228)]
        public float _227 { get; set; }


        [ColumnName("228"), LoadColumn(229)]
        public float _228 { get; set; }


        [ColumnName("229"), LoadColumn(230)]
        public float _229 { get; set; }


        [ColumnName("230"), LoadColumn(231)]
        public float _230 { get; set; }


        [ColumnName("231"), LoadColumn(232)]
        public float _231 { get; set; }


        [ColumnName("232"), LoadColumn(233)]
        public float _232 { get; set; }


        [ColumnName("233"), LoadColumn(234)]
        public float _233 { get; set; }


        [ColumnName("234"), LoadColumn(235)]
        public float _234 { get; set; }


        [ColumnName("235"), LoadColumn(236)]
        public float _235 { get; set; }


        [ColumnName("236"), LoadColumn(237)]
        public float _236 { get; set; }


        [ColumnName("237"), LoadColumn(238)]
        public float _237 { get; set; }


        [ColumnName("238"), LoadColumn(239)]
        public float _238 { get; set; }


        [ColumnName("239"), LoadColumn(240)]
        public float _239 { get; set; }


        [ColumnName("240"), LoadColumn(241)]
        public float _240 { get; set; }


        [ColumnName("241"), LoadColumn(242)]
        public float _241 { get; set; }


        [ColumnName("242"), LoadColumn(243)]
        public float _242 { get; set; }


        [ColumnName("243"), LoadColumn(244)]
        public float _243 { get; set; }


        [ColumnName("244"), LoadColumn(245)]
        public float _244 { get; set; }


        [ColumnName("245"), LoadColumn(246)]
        public float _245 { get; set; }


        [ColumnName("246"), LoadColumn(247)]
        public float _246 { get; set; }


        [ColumnName("247"), LoadColumn(248)]
        public float _247 { get; set; }


        [ColumnName("248"), LoadColumn(249)]
        public float _248 { get; set; }


        [ColumnName("249"), LoadColumn(250)]
        public float _249 { get; set; }


        [ColumnName("250"), LoadColumn(251)]
        public float _250 { get; set; }


        [ColumnName("251"), LoadColumn(252)]
        public float _251 { get; set; }


        [ColumnName("252"), LoadColumn(253)]
        public float _252 { get; set; }


        [ColumnName("253"), LoadColumn(254)]
        public float _253 { get; set; }


        [ColumnName("254"), LoadColumn(255)]
        public float _254 { get; set; }


        [ColumnName("255"), LoadColumn(256)]
        public float _255 { get; set; }


        [ColumnName("256"), LoadColumn(257)]
        public float _256 { get; set; }


        [ColumnName("257"), LoadColumn(258)]
        public float _257 { get; set; }


        [ColumnName("258"), LoadColumn(259)]
        public float _258 { get; set; }


        [ColumnName("259"), LoadColumn(260)]
        public float _259 { get; set; }


        [ColumnName("260"), LoadColumn(261)]
        public float _260 { get; set; }


        [ColumnName("261"), LoadColumn(262)]
        public float _261 { get; set; }


        [ColumnName("262"), LoadColumn(263)]
        public float _262 { get; set; }


        [ColumnName("263"), LoadColumn(264)]
        public float _263 { get; set; }


        [ColumnName("264"), LoadColumn(265)]
        public float _264 { get; set; }


        [ColumnName("265"), LoadColumn(266)]
        public float _265 { get; set; }


        [ColumnName("266"), LoadColumn(267)]
        public float _266 { get; set; }


        [ColumnName("267"), LoadColumn(268)]
        public float _267 { get; set; }


        [ColumnName("268"), LoadColumn(269)]
        public float _268 { get; set; }


        [ColumnName("269"), LoadColumn(270)]
        public float _269 { get; set; }


        [ColumnName("270"), LoadColumn(271)]
        public float _270 { get; set; }


        [ColumnName("271"), LoadColumn(272)]
        public float _271 { get; set; }


        [ColumnName("272"), LoadColumn(273)]
        public float _272 { get; set; }


        [ColumnName("273"), LoadColumn(274)]
        public float _273 { get; set; }


        [ColumnName("274"), LoadColumn(275)]
        public float _274 { get; set; }


        [ColumnName("275"), LoadColumn(276)]
        public float _275 { get; set; }


        [ColumnName("276"), LoadColumn(277)]
        public float _276 { get; set; }


        [ColumnName("277"), LoadColumn(278)]
        public float _277 { get; set; }


        [ColumnName("278"), LoadColumn(279)]
        public float _278 { get; set; }


        [ColumnName("279"), LoadColumn(280)]
        public float _279 { get; set; }


        [ColumnName("280"), LoadColumn(281)]
        public float _280 { get; set; }


        [ColumnName("281"), LoadColumn(282)]
        public float _281 { get; set; }


        [ColumnName("282"), LoadColumn(283)]
        public float _282 { get; set; }


        [ColumnName("283"), LoadColumn(284)]
        public float _283 { get; set; }


        [ColumnName("284"), LoadColumn(285)]
        public float _284 { get; set; }


        [ColumnName("285"), LoadColumn(286)]
        public float _285 { get; set; }


        [ColumnName("286"), LoadColumn(287)]
        public float _286 { get; set; }


        [ColumnName("287"), LoadColumn(288)]
        public float _287 { get; set; }


        [ColumnName("288"), LoadColumn(289)]
        public float _288 { get; set; }


        [ColumnName("289"), LoadColumn(290)]
        public float _289 { get; set; }


        [ColumnName("290"), LoadColumn(291)]
        public float _290 { get; set; }


        [ColumnName("291"), LoadColumn(292)]
        public float _291 { get; set; }


        [ColumnName("292"), LoadColumn(293)]
        public float _292 { get; set; }


        [ColumnName("293"), LoadColumn(294)]
        public float _293 { get; set; }


        [ColumnName("294"), LoadColumn(295)]
        public float _294 { get; set; }


        [ColumnName("295"), LoadColumn(296)]
        public float _295 { get; set; }


        [ColumnName("296"), LoadColumn(297)]
        public float _296 { get; set; }


        [ColumnName("297"), LoadColumn(298)]
        public float _297 { get; set; }


        [ColumnName("298"), LoadColumn(299)]
        public float _298 { get; set; }


        [ColumnName("299"), LoadColumn(300)]
        public float _299 { get; set; }


        [ColumnName("300"), LoadColumn(301)]
        public float _300 { get; set; }


        [ColumnName("301"), LoadColumn(302)]
        public float _301 { get; set; }


        [ColumnName("302"), LoadColumn(303)]
        public float _302 { get; set; }


        [ColumnName("303"), LoadColumn(304)]
        public float _303 { get; set; }


        [ColumnName("304"), LoadColumn(305)]
        public float _304 { get; set; }


        [ColumnName("305"), LoadColumn(306)]
        public float _305 { get; set; }


        [ColumnName("306"), LoadColumn(307)]
        public float _306 { get; set; }


        [ColumnName("307"), LoadColumn(308)]
        public float _307 { get; set; }


        [ColumnName("308"), LoadColumn(309)]
        public float _308 { get; set; }


        [ColumnName("309"), LoadColumn(310)]
        public float _309 { get; set; }


        [ColumnName("310"), LoadColumn(311)]
        public float _310 { get; set; }


        [ColumnName("311"), LoadColumn(312)]
        public float _311 { get; set; }


        [ColumnName("312"), LoadColumn(313)]
        public float _312 { get; set; }


        [ColumnName("313"), LoadColumn(314)]
        public float _313 { get; set; }


        [ColumnName("314"), LoadColumn(315)]
        public float _314 { get; set; }


        [ColumnName("315"), LoadColumn(316)]
        public float _315 { get; set; }


        [ColumnName("316"), LoadColumn(317)]
        public float _316 { get; set; }


        [ColumnName("317"), LoadColumn(318)]
        public float _317 { get; set; }


        [ColumnName("318"), LoadColumn(319)]
        public float _318 { get; set; }


        [ColumnName("319"), LoadColumn(320)]
        public float _319 { get; set; }


        [ColumnName("320"), LoadColumn(321)]
        public float _320 { get; set; }


        [ColumnName("321"), LoadColumn(322)]
        public float _321 { get; set; }


        [ColumnName("322"), LoadColumn(323)]
        public float _322 { get; set; }


        [ColumnName("323"), LoadColumn(324)]
        public float _323 { get; set; }


        [ColumnName("324"), LoadColumn(325)]
        public float _324 { get; set; }


        [ColumnName("325"), LoadColumn(326)]
        public float _325 { get; set; }


        [ColumnName("326"), LoadColumn(327)]
        public float _326 { get; set; }


        [ColumnName("327"), LoadColumn(328)]
        public float _327 { get; set; }


        [ColumnName("328"), LoadColumn(329)]
        public float _328 { get; set; }


        [ColumnName("329"), LoadColumn(330)]
        public float _329 { get; set; }


        [ColumnName("330"), LoadColumn(331)]
        public float _330 { get; set; }


        [ColumnName("331"), LoadColumn(332)]
        public float _331 { get; set; }


        [ColumnName("332"), LoadColumn(333)]
        public float _332 { get; set; }


        [ColumnName("333"), LoadColumn(334)]
        public float _333 { get; set; }


        [ColumnName("334"), LoadColumn(335)]
        public float _334 { get; set; }


        [ColumnName("335"), LoadColumn(336)]
        public float _335 { get; set; }


        [ColumnName("336"), LoadColumn(337)]
        public float _336 { get; set; }


        [ColumnName("337"), LoadColumn(338)]
        public float _337 { get; set; }


        [ColumnName("338"), LoadColumn(339)]
        public float _338 { get; set; }


        [ColumnName("339"), LoadColumn(340)]
        public float _339 { get; set; }


        [ColumnName("340"), LoadColumn(341)]
        public float _340 { get; set; }


        [ColumnName("341"), LoadColumn(342)]
        public float _341 { get; set; }


        [ColumnName("342"), LoadColumn(343)]
        public float _342 { get; set; }


        [ColumnName("343"), LoadColumn(344)]
        public float _343 { get; set; }


        [ColumnName("344"), LoadColumn(345)]
        public float _344 { get; set; }


        [ColumnName("345"), LoadColumn(346)]
        public float _345 { get; set; }


        [ColumnName("346"), LoadColumn(347)]
        public float _346 { get; set; }


        [ColumnName("347"), LoadColumn(348)]
        public float _347 { get; set; }


        [ColumnName("348"), LoadColumn(349)]
        public float _348 { get; set; }


        [ColumnName("349"), LoadColumn(350)]
        public float _349 { get; set; }


        [ColumnName("350"), LoadColumn(351)]
        public float _350 { get; set; }


        [ColumnName("351"), LoadColumn(352)]
        public float _351 { get; set; }


        [ColumnName("352"), LoadColumn(353)]
        public float _352 { get; set; }


        [ColumnName("353"), LoadColumn(354)]
        public float _353 { get; set; }


        [ColumnName("354"), LoadColumn(355)]
        public float _354 { get; set; }


        [ColumnName("355"), LoadColumn(356)]
        public float _355 { get; set; }


        [ColumnName("356"), LoadColumn(357)]
        public float _356 { get; set; }


        [ColumnName("357"), LoadColumn(358)]
        public float _357 { get; set; }


        [ColumnName("358"), LoadColumn(359)]
        public float _358 { get; set; }


        [ColumnName("359"), LoadColumn(360)]
        public float _359 { get; set; }


        [ColumnName("360"), LoadColumn(361)]
        public float _360 { get; set; }


        [ColumnName("361"), LoadColumn(362)]
        public float _361 { get; set; }


        [ColumnName("362"), LoadColumn(363)]
        public float _362 { get; set; }


        [ColumnName("363"), LoadColumn(364)]
        public float _363 { get; set; }


        [ColumnName("364"), LoadColumn(365)]
        public float _364 { get; set; }


        [ColumnName("365"), LoadColumn(366)]
        public float _365 { get; set; }


        [ColumnName("366"), LoadColumn(367)]
        public float _366 { get; set; }


        [ColumnName("367"), LoadColumn(368)]
        public float _367 { get; set; }


        [ColumnName("368"), LoadColumn(369)]
        public float _368 { get; set; }


        [ColumnName("369"), LoadColumn(370)]
        public float _369 { get; set; }


        [ColumnName("370"), LoadColumn(371)]
        public float _370 { get; set; }


        [ColumnName("371"), LoadColumn(372)]
        public float _371 { get; set; }


        [ColumnName("372"), LoadColumn(373)]
        public float _372 { get; set; }


        [ColumnName("373"), LoadColumn(374)]
        public float _373 { get; set; }


        [ColumnName("374"), LoadColumn(375)]
        public float _374 { get; set; }


        [ColumnName("375"), LoadColumn(376)]
        public float _375 { get; set; }


        [ColumnName("376"), LoadColumn(377)]
        public float _376 { get; set; }


        [ColumnName("377"), LoadColumn(378)]
        public float _377 { get; set; }


        [ColumnName("378"), LoadColumn(379)]
        public float _378 { get; set; }


        [ColumnName("379"), LoadColumn(380)]
        public float _379 { get; set; }


        [ColumnName("380"), LoadColumn(381)]
        public float _380 { get; set; }


        [ColumnName("381"), LoadColumn(382)]
        public float _381 { get; set; }


        [ColumnName("382"), LoadColumn(383)]
        public float _382 { get; set; }


        [ColumnName("383"), LoadColumn(384)]
        public float _383 { get; set; }


        [ColumnName("384"), LoadColumn(385)]
        public float _384 { get; set; }


        [ColumnName("385"), LoadColumn(386)]
        public float _385 { get; set; }


        [ColumnName("386"), LoadColumn(387)]
        public float _386 { get; set; }


        [ColumnName("387"), LoadColumn(388)]
        public float _387 { get; set; }


        [ColumnName("388"), LoadColumn(389)]
        public float _388 { get; set; }


        [ColumnName("389"), LoadColumn(390)]
        public float _389 { get; set; }


        [ColumnName("390"), LoadColumn(391)]
        public float _390 { get; set; }


        [ColumnName("391"), LoadColumn(392)]
        public float _391 { get; set; }


        [ColumnName("392"), LoadColumn(393)]
        public float _392 { get; set; }


        [ColumnName("393"), LoadColumn(394)]
        public float _393 { get; set; }


        [ColumnName("394"), LoadColumn(395)]
        public float _394 { get; set; }


        [ColumnName("395"), LoadColumn(396)]
        public float _395 { get; set; }


        [ColumnName("396"), LoadColumn(397)]
        public float _396 { get; set; }


        [ColumnName("397"), LoadColumn(398)]
        public float _397 { get; set; }


        [ColumnName("398"), LoadColumn(399)]
        public float _398 { get; set; }


        [ColumnName("399"), LoadColumn(400)]
        public float _399 { get; set; }


        [ColumnName("400"), LoadColumn(401)]
        public float _400 { get; set; }


        [ColumnName("401"), LoadColumn(402)]
        public float _401 { get; set; }


        [ColumnName("402"), LoadColumn(403)]
        public float _402 { get; set; }


        [ColumnName("403"), LoadColumn(404)]
        public float _403 { get; set; }


        [ColumnName("404"), LoadColumn(405)]
        public float _404 { get; set; }


        [ColumnName("405"), LoadColumn(406)]
        public float _405 { get; set; }


        [ColumnName("406"), LoadColumn(407)]
        public float _406 { get; set; }


        [ColumnName("407"), LoadColumn(408)]
        public float _407 { get; set; }


        [ColumnName("408"), LoadColumn(409)]
        public float _408 { get; set; }


        [ColumnName("409"), LoadColumn(410)]
        public float _409 { get; set; }


        [ColumnName("410"), LoadColumn(411)]
        public float _410 { get; set; }


        [ColumnName("411"), LoadColumn(412)]
        public float _411 { get; set; }


        [ColumnName("412"), LoadColumn(413)]
        public float _412 { get; set; }


        [ColumnName("413"), LoadColumn(414)]
        public float _413 { get; set; }


        [ColumnName("414"), LoadColumn(415)]
        public float _414 { get; set; }


        [ColumnName("415"), LoadColumn(416)]
        public float _415 { get; set; }


        [ColumnName("416"), LoadColumn(417)]
        public float _416 { get; set; }


        [ColumnName("417"), LoadColumn(418)]
        public float _417 { get; set; }


        [ColumnName("418"), LoadColumn(419)]
        public float _418 { get; set; }


        [ColumnName("419"), LoadColumn(420)]
        public float _419 { get; set; }


        [ColumnName("420"), LoadColumn(421)]
        public float _420 { get; set; }


        [ColumnName("421"), LoadColumn(422)]
        public float _421 { get; set; }


        [ColumnName("422"), LoadColumn(423)]
        public float _422 { get; set; }


        [ColumnName("423"), LoadColumn(424)]
        public float _423 { get; set; }


        [ColumnName("424"), LoadColumn(425)]
        public float _424 { get; set; }


        [ColumnName("425"), LoadColumn(426)]
        public float _425 { get; set; }


        [ColumnName("426"), LoadColumn(427)]
        public float _426 { get; set; }


        [ColumnName("427"), LoadColumn(428)]
        public float _427 { get; set; }


        [ColumnName("428"), LoadColumn(429)]
        public float _428 { get; set; }


        [ColumnName("429"), LoadColumn(430)]
        public float _429 { get; set; }


        [ColumnName("430"), LoadColumn(431)]
        public float _430 { get; set; }


        [ColumnName("431"), LoadColumn(432)]
        public float _431 { get; set; }


        [ColumnName("432"), LoadColumn(433)]
        public float _432 { get; set; }


        [ColumnName("433"), LoadColumn(434)]
        public float _433 { get; set; }


        [ColumnName("434"), LoadColumn(435)]
        public float _434 { get; set; }


        [ColumnName("435"), LoadColumn(436)]
        public float _435 { get; set; }


        [ColumnName("436"), LoadColumn(437)]
        public float _436 { get; set; }


        [ColumnName("437"), LoadColumn(438)]
        public float _437 { get; set; }


        [ColumnName("438"), LoadColumn(439)]
        public float _438 { get; set; }


        [ColumnName("439"), LoadColumn(440)]
        public float _439 { get; set; }


        [ColumnName("440"), LoadColumn(441)]
        public float _440 { get; set; }


        [ColumnName("441"), LoadColumn(442)]
        public float _441 { get; set; }


        [ColumnName("442"), LoadColumn(443)]
        public float _442 { get; set; }


        [ColumnName("443"), LoadColumn(444)]
        public float _443 { get; set; }


        [ColumnName("444"), LoadColumn(445)]
        public float _444 { get; set; }


        [ColumnName("445"), LoadColumn(446)]
        public float _445 { get; set; }


        [ColumnName("446"), LoadColumn(447)]
        public float _446 { get; set; }


        [ColumnName("447"), LoadColumn(448)]
        public float _447 { get; set; }


        [ColumnName("448"), LoadColumn(449)]
        public float _448 { get; set; }


        [ColumnName("449"), LoadColumn(450)]
        public float _449 { get; set; }


        [ColumnName("450"), LoadColumn(451)]
        public float _450 { get; set; }


        [ColumnName("451"), LoadColumn(452)]
        public float _451 { get; set; }


        [ColumnName("452"), LoadColumn(453)]
        public float _452 { get; set; }


        [ColumnName("453"), LoadColumn(454)]
        public float _453 { get; set; }


        [ColumnName("454"), LoadColumn(455)]
        public float _454 { get; set; }


        [ColumnName("455"), LoadColumn(456)]
        public float _455 { get; set; }


        [ColumnName("456"), LoadColumn(457)]
        public float _456 { get; set; }


        [ColumnName("457"), LoadColumn(458)]
        public float _457 { get; set; }


        [ColumnName("458"), LoadColumn(459)]
        public float _458 { get; set; }


        [ColumnName("459"), LoadColumn(460)]
        public float _459 { get; set; }


        [ColumnName("460"), LoadColumn(461)]
        public float _460 { get; set; }


        [ColumnName("461"), LoadColumn(462)]
        public float _461 { get; set; }


        [ColumnName("462"), LoadColumn(463)]
        public float _462 { get; set; }


        [ColumnName("463"), LoadColumn(464)]
        public float _463 { get; set; }


        [ColumnName("464"), LoadColumn(465)]
        public float _464 { get; set; }


        [ColumnName("465"), LoadColumn(466)]
        public float _465 { get; set; }


        [ColumnName("466"), LoadColumn(467)]
        public float _466 { get; set; }


        [ColumnName("467"), LoadColumn(468)]
        public float _467 { get; set; }


        [ColumnName("468"), LoadColumn(469)]
        public float _468 { get; set; }


        [ColumnName("469"), LoadColumn(470)]
        public float _469 { get; set; }


        [ColumnName("470"), LoadColumn(471)]
        public float _470 { get; set; }


        [ColumnName("471"), LoadColumn(472)]
        public float _471 { get; set; }


        [ColumnName("472"), LoadColumn(473)]
        public float _472 { get; set; }


        [ColumnName("473"), LoadColumn(474)]
        public float _473 { get; set; }


        [ColumnName("474"), LoadColumn(475)]
        public float _474 { get; set; }


        [ColumnName("475"), LoadColumn(476)]
        public float _475 { get; set; }


        [ColumnName("476"), LoadColumn(477)]
        public float _476 { get; set; }


        [ColumnName("477"), LoadColumn(478)]
        public float _477 { get; set; }


        [ColumnName("478"), LoadColumn(479)]
        public float _478 { get; set; }


        [ColumnName("479"), LoadColumn(480)]
        public float _479 { get; set; }


    }
}
